name: FSDIYSpad Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - g1000nxi_pfd1
          - g1000nxi_mfd
          - g1000nxi_pfd2
          - gma1347
          - gcu478

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
            ~/.platformio/platforms
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build firmware
        if: ${{ matrix.environment == 'g1000nxi_pfd1' }}
        env:
          ENV_MESSAGE: "Building for G1000 PFD1"
          PLATFORMIO_BUILD_FLAGS: |
            --build-flag=-D SPAD_AUTHKEY=\"authkey\"
            --build-flag=-D SPAD_DEVICEVERSION=0.5
            --build-flag=-D SPAD_DEVICEID=\"{guid}\"
        run: |          
          echo $ENV_MESSAGE         
          echo $PLATFORMIO_BUILD_FLAGS
          pio run -e ${{ matrix.environment }}
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: .pio/build/${{ matrix.environment }}/firmware.hex
