name: Dev Release

on:
  push:
    branches:
      - develop
      - main
    tags-ignore:
      - '**'  # Don't trigger on any tag pushes

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit