name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Semantic versioning: v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: firmware-*
          path: artifacts

      - name: Get tag name
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Prepare release files
        run: |
          mkdir -p release
          
          # Copy and rename files with version
          for dir in artifacts/firmware-*; do
            env_name=$(basename "$dir" | sed 's/firmware-//')
            if [ -f "$dir/firmware.hex" ]; then
              cp "$dir/firmware.hex" "release/fsdiy-spad-${env_name}-${{ needs.build.outputs.version }}.hex"
            fi
          done
          
          cd release
          sha256sum *.hex > checksums.txt
          
          # Create release info file
          cat > RELEASE-INFO.txt << EOF
          FSDIY SPAD Firmware Release
          ===========================
          Version: ${{ needs.build.outputs.version }}
          Release Date: $(date +%Y-%m-%d)
          
          Included Firmware:
          - G1000 NXi PFD1
          - G1000 NXi MFD
          - G1000 NXi PFD2
          - GMA1347 Audio Panel
          - GCU478 Autopilot
          
          Installation:
          1. Download the appropriate .hex file for your device
          2. Flash using your preferred Arduino upload tool
          3. Verify checksums.txt for file integrity
          4. Add a serial device inside SPAD.  Be sure to select the correct COM port.  Default settings are fine.
          5. Restart SPAD.
          
          **COMING SOON** SPAD.neXt profiles.
          
          For more information, see the README.md in the repository.
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          generate_release_notes: true
          draft: false
          prerelease: false
          body: |
            ## FSDIY SPAD Firmware ${{ needs.build.outputs.version }}
            
            ### Download the firmware for your device:
            - **G1000 NXi PFD1**: `fsdiy-spad-g1000nxi_pfd1-${{ needs.build.outputs.version }}.hex`
            - **G1000 NXi MFD**: `fsdiy-spad-g1000nxi_mfd-${{ needs.build.outputs.version }}.hex`
            - **G1000 NXi PFD2**: `fsdiy-spad-g1000nxi_pfd2-${{ needs.build.outputs.version }}.hex`
            - **GMA1347**: `fsdiy-spad-gma1347-${{ needs.build.outputs.version }}.hex`
            - **GCU478**: `fsdiy-spad-gcu478-${{ needs.build.outputs.version }}.hex`
            
            See `checksums.txt` for SHA256 checksums.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}